SELECT * FROM DEV_CSM_DB.CORPORATE.HR_LOCATIONS_ALL
WHERE inactive_date IS NOT NULL
LIMIT 10;

DESCRIBE TABLE DEV_CSM_DB.CORPORATE.HR_LOCATIONS_ALL;

SELECT * FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V
WHERE ISOPEN = TRUE
LIMIT 10;

SELECT COUNT(*) FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V
WHERE ISOPEN = TRUE;

SELECT DISTINCT(CMPYCODE) FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V;

SELECT * FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V
WHERE CMPYCODE in ('70', 'S2', '20')
AND ISOPEN = true;

SELECT * FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V
WHERE CMPYCODE = 'H6';

SELECT * FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V
WHERE LOCATIONID = '7108';

SELECT * FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V
WHERE ZIP LIKE '%27615%';

SELECT * FROM PROD_CSM_DB.CORPORATE.LOCATIONS_ALL_V
WHERE TO_VARCHAR(CMPYCODE) IN ('75', '70', 'S2', '30');